import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Product } from '@/hooks/useProducts';
import { formatCurrency, formatPercentage } from '@/lib/calculations';

/**
 * Generate a branded PDF cost sheet for a single product
 */
export function exportProductCostSheetPDF(product: Product) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // Header bar
  doc.setFillColor(180, 90, 30); // Primary amber
  doc.rect(0, 0, pageWidth, 28, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('COGS Calculator', 14, 16);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Product Cost Sheet', 14, 23);
  
  // Date
  doc.setFontSize(9);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 14, 16, { align: 'right' });

  let y = 40;

  // Product name
  doc.setTextColor(40, 35, 30);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text(product.name, 14, y);
  y += 8;
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(120, 110, 100);
  doc.text(`Type: ${product.product_type} · ${product.fill_weight_per_unit} ${product.fill_unit} per unit · ${product.units_per_batch} units/batch`, 14, y);
  if (product.selling_pack_size > 1) {
    y += 5;
    doc.text(`Selling pack size: ${product.selling_pack_size} units`, 14, y);
  }
  y += 12;

  // COGS Breakdown table
  doc.setTextColor(40, 35, 30);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Cost of Goods Sold (COGS)', 14, y);
  y += 3;

  const cogsData = [
    ['Materials Cost', formatCurrency(product.materials_cost_per_unit, 4)],
    ['Packaging Cost', formatCurrency(product.packaging_cost_per_unit, 4)],
    ['Labor Cost', formatCurrency(product.labor_cost_per_unit, 4)],
    ['Shipping / Overhead', formatCurrency(product.shipping_cost_per_unit, 4)],
  ];

  autoTable(doc, {
    startY: y,
    head: [['Cost Component', 'Per Unit']],
    body: cogsData,
    foot: [['Total COGS per Unit', formatCurrency(product.total_cogs_per_unit)]],
    theme: 'grid',
    headStyles: { fillColor: [180, 90, 30], textColor: 255, fontStyle: 'bold', fontSize: 10 },
    footStyles: { fillColor: [245, 240, 235], textColor: [40, 35, 30], fontStyle: 'bold', fontSize: 11 },
    bodyStyles: { fontSize: 10 },
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: 14, right: 14 },
  });

  y = (doc as any).lastAutoTable.finalY + 14;

  // Pricing Summary
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Pricing Summary', 14, y);
  y += 3;

  const packCOGS = product.total_cogs_per_unit * (product.selling_pack_size || 1);
  const wholesaleMargin = product.wholesale_price > 0
    ? ((product.wholesale_price - packCOGS) / product.wholesale_price) * 100
    : 0;
  const retailMargin = product.retail_price > 0
    ? ((product.retail_price - packCOGS) / product.retail_price) * 100
    : 0;

  const pricingData = [
    ['Wholesale Markup', `${product.wholesale_markup}%`],
    ['Wholesale Price', formatCurrency(product.wholesale_price)],
    ['Wholesale Margin', formatPercentage(wholesaleMargin)],
    ['Retail Markup', `${product.retail_markup}%`],
    ['DTC Retail Price', formatCurrency(product.retail_price)],
    ['DTC Retail Margin', formatPercentage(retailMargin)],
  ];

  autoTable(doc, {
    startY: y,
    head: [['Metric', 'Value']],
    body: pricingData,
    theme: 'grid',
    headStyles: { fillColor: [180, 90, 30], textColor: 255, fontStyle: 'bold', fontSize: 10 },
    bodyStyles: { fontSize: 10 },
    columnStyles: { 1: { halign: 'right' } },
    margin: { left: 14, right: 14 },
  });

  y = (doc as any).lastAutoTable.finalY + 14;

  // Production Details
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Production Details', 14, y);
  y += 3;

  const productionData = [
    ['Labor Rate', `${formatCurrency(product.labor_rate_per_hour)}/hr`],
    ['Labor Hours per Batch', `${product.labor_hours_per_batch} hrs`],
    ['Shipping Overhead per Batch', formatCurrency(product.shipping_overhead_per_batch)],
    ['Units per Batch', `${product.units_per_batch}`],
  ];

  autoTable(doc, {
    startY: y,
    body: productionData,
    theme: 'plain',
    bodyStyles: { fontSize: 10 },
    columnStyles: { 1: { halign: 'right', fontStyle: 'bold' } },
    margin: { left: 14, right: 14 },
  });

  // Footer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setDrawColor(200, 190, 180);
  doc.line(14, pageHeight - 18, pageWidth - 14, pageHeight - 18);
  doc.setFontSize(8);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(150, 140, 130);
  doc.text('Generated by COGS Calculator', 14, pageHeight - 12);
  doc.text('Confidential — For internal use only', pageWidth - 14, pageHeight - 12, { align: 'right' });

  // Save
  const safeName = product.name.replace(/[^a-zA-Z0-9]/g, '-').toLowerCase();
  doc.save(`${safeName}-cost-sheet.pdf`);
}

/**
 * Generate a retail store performance report PDF
 */
export function exportRetailPerformanceReportPDF(
  storeMetrics: Array<{
    storeName: string;
    productCount: number;
    avgRetailPrice: number;
    avgWholesaleMargin: number;
    unitsPerMonth: number;
    unitsPerYear: number;
    products: Array<{
      name: string;
      retailPrice: number;
      wholesalePrice: number;
      unitsSold: number;
      unitsYear: number;
      margin: number;
    }>;
  }>,
  monthLabel: string
) {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Header
  doc.setFillColor(180, 90, 30);
  doc.rect(0, 0, pageWidth, 28, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text('COGS Calculator', 14, 16);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('Retail Store Performance Report', 14, 23);
  doc.setFontSize(9);
  doc.text(`Period: ${monthLabel}`, pageWidth - 14, 16, { align: 'right' });
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, pageWidth - 14, 22, { align: 'right' });

  let y = 40;

  // Summary table
  doc.setTextColor(40, 35, 30);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Store Summary', 14, y);
  y += 3;

  const summaryData = storeMetrics.map(s => [
    s.storeName,
    s.productCount.toString(),
    s.unitsPerMonth.toString(),
    s.unitsPerYear.toString(),
    formatCurrency(s.avgRetailPrice),
    formatPercentage(s.avgWholesaleMargin),
  ]);

  autoTable(doc, {
    startY: y,
    head: [['Store', 'Products', 'Units/Mo', 'Units/Yr', 'Avg Retail', 'Margin']],
    body: summaryData,
    theme: 'grid',
    headStyles: { fillColor: [180, 90, 30], textColor: 255, fontStyle: 'bold', fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    columnStyles: {
      1: { halign: 'center' },
      2: { halign: 'right' },
      3: { halign: 'right' },
      4: { halign: 'right' },
      5: { halign: 'right' },
    },
    margin: { left: 14, right: 14 },
  });

  y = (doc as any).lastAutoTable.finalY + 14;

  // Per-store product breakdown
  for (const store of storeMetrics) {
    if (store.products.length === 0) continue;

    // Check if we need a new page
    if (y > 240) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(40, 35, 30);
    doc.text(store.storeName, 14, y);
    y += 3;

    const productData = store.products.map(p => [
      p.name,
      formatCurrency(p.wholesalePrice),
      formatCurrency(p.retailPrice),
      p.unitsSold.toString(),
      p.unitsYear.toString(),
      formatPercentage(p.margin),
    ]);

    autoTable(doc, {
      startY: y,
      head: [['Product', 'Wholesale', 'Retail', 'Sold/Mo', 'Sold/Yr', 'Margin']],
      body: productData,
      theme: 'striped',
      headStyles: { fillColor: [100, 90, 80], textColor: 255, fontSize: 8 },
      bodyStyles: { fontSize: 8 },
      columnStyles: {
        1: { halign: 'right' },
        2: { halign: 'right' },
        3: { halign: 'right' },
        4: { halign: 'right' },
        5: { halign: 'right' },
      },
      margin: { left: 14, right: 14 },
    });

    y = (doc as any).lastAutoTable.finalY + 12;
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setDrawColor(200, 190, 180);
    doc.line(14, pageHeight - 18, pageWidth - 14, pageHeight - 18);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(150, 140, 130);
    doc.text('Generated by COGS Calculator', 14, pageHeight - 12);
    doc.text(`Page ${i} of ${pageCount}`, pageWidth - 14, pageHeight - 12, { align: 'right' });
  }

  const date = new Date().toISOString().split('T')[0];
  doc.save(`retail-performance-${date}.pdf`);
}
